baseurl = "https://schmitzlab.github.io/stable-transgenerational-inheritance-of-DNA-methylation/"
languageCode = "en-us"
title = "Stable Transgenerational Inheritance of DNA Methylation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
publishDir = "../docs"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Brigitte Hofmeister"
	description = "Epigenotyping"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/schmitzlab/stable-transgenerational-inheritance-of-DNA-methylation"

	version = "1.0.0"
	logo = "i"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "light-green"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = ""
	email   = ""


[[menu.main]]
	name   = "Epigenotyping"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "/getting-started"
	weight = 20


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
