baseurl = "https://schmitzlab.github.io/stable-transgenerational-inheritance-of-DNA-methylation/"
languageCode = "en-us"
title = "Inheritance of DNA Methylation"
theme = "hugo-material-docs"
metadataformat = "toml"
canonifyurls = true
publishDir = "../docs"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Brigitte Hofmeister"
	description = "Epigenotyping"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/schmitzlab/stable-transgenerational-inheritance-of-DNA-methylation"

	version = ""
	logo = ""
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["custom.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "cyan"
    	accent  = "red"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = ""
	email   = ""


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 20
    
[[menu.main]]
    name    = "Transgeneration inheritance"
    url     = "transgenerational/"
    weight  = 30

[[menu.main]]
	name   = "Epigenotyping"
	url    = "epigenotyping/"
	weight = 40
    
[[menu.main]]
	name   = "Appendix"
	url    = "/appendix"
	weight = 50

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[taxonomies]
    tag = ""
    category = ""
